language: node_js
sudo: false

node_js:
  - 0.12

install: 
  - npm install
  - npm install -g gulp

script:
  - gulp
  - gulp test
  - npm start

before_deploy:
- gem install mime-types -v 2.6.2

deploy:
  - provider: opsworks
    access-key-id: 
      secure: "JhjnySnx9vQMPLCKMPE4rlLRWSAeYW1OeEzR/UdMjIuJT6woJ1Aq+uFVulhi+9KFOgMN8/yo58K9cbnnSjYMEnhmWn0pnKPaj/sbwQfRH7ln4gN/U74CBnTorLFBgH09Qnh4KWbYo6xzW/RKFnkhrSdR8pLiMc0d4r30XcoHJZs="
    secret-access-key: 
      secure: "lb/JsIoh2d71fwjwOPxiauHobWW8Zji6lrsTpB3Eb1LkQ55zvpwUo4vlBcB+1u6FgCUyZyD5e5dheWBjr46uql8CjHvnu/ZlZoQXzk+mYVViE5FvUwypk4YP4czJwJv6/E4JAdU12eBDpPF96hp3/iyx/JJcUhC7kg2XSWqmGxs="
    app-id: 4591eee2-cb84-41a5-baa2-fd52009cfb38
    on:
      repo: webRunes/webGold-WRIO-App
  - provider: s3
    access_key_id:
      secure: e6CpXbDmuJOZTf/kyurb4bk8kn83pj3Knq9XxmkaqvXFytPlyzV1aJV440Ha+rci5dZn5yktavx6Hl13FGsRRYx7wYKPz8Lh+4BiOqZTT/ZiFAITLffu3e2uSSCrp+cGNi/cIweFSTp0fA8vcoUbMbxfa6d1O4hTiY8DMPvpnjQ=
    secret_access_key:
      secure: oZLlSoCrrz6s5Ylv/uec+fQTwZFz5a6N3YkmYC4h5dqkW+UrTBHifXGOZACLzjkyXga8/oKXKTHCiKCQ0BnODZyauoTH/qWy7PK1ckvg9QWWyM/w+HAf7mipFC+TeGdI0cEcX2VDsjcVLUuX2sjTPFHl9hKbX1CSpcPfuIA0Ikg=
    bucket: wrioos.com
    upload-dir: webGold-WRIO-App
    acl: public_read

